#!/usr/bin/env bash
if bluetoothctl show 2>/dev/null | grep -q "Powered: yes"; then
  bluetoothctl power off >/dev/null && notify-send "Bluetooth" "Off"
else
  bluetoothctl power on >/dev/null && notify-send "Bluetooth" "On"
fi
