#!/usr/bin/env bash
if command -v blueman-manager >/dev/null 2>&1; then
  exec blueman-manager
elif command -v gnome-control-center >/dev/null 2>&1; then
  exec gnome-control-center bluetooth
else
  notify-send "Bluetooth" "Bluetooth manager GUI tidak ditemukan"
fi
