-- Generated by hyprlang2lua. Manual review completed before loading Hyprland.
local HOME = assert(os.getenv("HOME"), "HOME environment variable is not set")


local hypr_border_size = 2
local hypr_gaps_in = 4
local hypr_gaps_out = 6
local hypr_rounding = 10
local gradient_angle = "45deg"
local active_border_col_1 = 0xFFB4A1DB
local active_border_col_2 = 0xFFD04E9D
local inactive_border_col_1 = "rgb(1e2030)"
local inactive_border_col_2 = "rgb(1e2030)"
local active_shadow_col = 0x66000000
local inactive_shadow_col = 0x66000000
local group_border_col = 0xFFDB695B
local group_border_active_col = 0xFF4BC66D
local notifycmd = "notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low"
local term = "~/.config/hypr/scripts/terminal"
local volume = "~/.config/hypr/scripts/volume"
local backlight = "~/.config/hypr/scripts/brightness"
local screenshot = "~/.config/hypr/scripts/screenshot"
local lockscreen = "hyprlock"
local wlogout = "~/.config/hypr/scripts/wlogout"
local colorpicker = "~/.config/hypr/scripts/colorpicker"
local emojipicker = "wofi-emoji"
local files = "thunar"
local editor = "geany"
local browser = "google-chrome-stable"
local rofi_launcher = "~/.config/hypr/scripts/rofi_launcher"
local rofi_runner = "~/.config/hypr/scripts/rofi_runner"
local rofi_music = "~/.config/hypr/scripts/rofi_music"
local rofi_network = "~/.config/hypr/scripts/rofi_network"
local rofi_powermenu = "~/.config/hypr/scripts/rofi_powermenu"
local rofi_screenshot = "~/.config/hypr/scripts/rofi_screenshot"
local wofi_launcher = "wofi -I"
local wofi_screenshot = "~/.config/sway/scripts/screenshot.sh"
local wofi_menu = "~/.config/hypr/scripts/wofi_menu"
local wofi_powermenu = "~/.config/hypr/scripts/wofi_powermenu"
local cheatsheet = "foot --app-id='foot-float' --config=\"" .. HOME .. "/.config/hypr/foot/foot.ini\" -t cheatsheet -e micro ~/.config/hypr/cheatsheet.md"
local background_swap = "~/.config/hypr/scripts/background"
local waybar_themes = "~/.config/hypr/waybar/scripts/change-theme.sh"
local screen_mode = "~/.config/hypr/scripts/screen"

-- Input gabungan untuk migrasi Hyprland Lua
-- Dibuat: 2026-08-11T13:18:04+07:00

-- ==========================================
-- Isi hyprtheme.conf
-- ==========================================
-- Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
--
-- Theme Elements & Colors for Hyprland.
-- Edited for Garuda Linux by yurihikari

-- Elements

-- Colors

-- ==========================================
-- Isi hyprland.conf
-- ==========================================
-- Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
--
-- Hyprland configuration file for Archcraft
-- Version: 0.22.0 Beta
-- Edited for Garuda Linux by yurihikari

---- Source Files -----------------------------------------------

---- General ----------------------------------------------------

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 5,
    bezier = "default",
    style = "popin 0%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 5,
    bezier = "default",
    style = "popin",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 5,
    bezier = "default",
    style = "slide",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fadeSwitch",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fadeShadow",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "default",
    style = "slide",
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

-- Blur Waybar layer
hl.layer_rule({
    name = "blur-waybar",
    match = { namespace = "waybar" },
    blur = true,
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.bind("SUPER + G", hl.dsp.group.toggle())
hl.bind("SUPER + G", hl.dsp.exec_cmd(notifycmd .. " 'Toggled Group Mode'"))
hl.bind("SUPER + H", hl.dsp.group.prev())
hl.bind("SUPER + L", hl.dsp.group.next())

hl.window_rule({
    name = "float-terminals",
    match = {
        class = "^(foot-float|kitty-float|term-float)$",
    },
    float = true,
})

hl.window_rule({
    name = "float-dialogs",
    match = {
        class = "^(yad|nm-connection-editor|pavucontrolk)$",
    },
    float = true,
})

hl.window_rule({
    name = "float-settings",
    match = {
        class = "^(xfce-polkit|kvantummanager|qt5ct)$",
    },
    float = true,
})

hl.window_rule({
    name = "float-viewers",
    match = {
        class = "^(feh|Viewnior|Gpicview|Gimp|MPlayer)$",
    },
    float = true,
})

hl.window_rule({
    name = "float-virtual",
    match = {
        class = "^(VirtualBox Manager|qemu|Qemu-system-x86_64)$",
    },
    float = true,
})

hl.window_rule({
    name = "float-file-progress",
    match = {
        title = "^File Operation Progress$",
    },
    float = true,
})

hl.window_rule({
    name = "float-confirm-replace",
    match = {
        title = "^Confirm to replace files$",
    },
    float = true,
})

hl.window_rule({
    name = "fullscreen-full",
    match = {
        class = "^(kitty-full|foot-full)$",
    },
    fullscreen = true,
})

hl.window_rule({
    name = "viewnior-size",
    match = {
        class = "^Viewnior$",
    },
    float = true,
    size = "60% 64%",
    center = true,
})

hl.window_rule({
    name = "waydroid-full",
    match = {
        class = "^Waydroid$",
    },
    fullscreen = true,
})

hl.window_rule({
    name = "anim-foot-full",
    match = {
        class = "^foot-full$",
    },
    animation = "slide down",
})

hl.window_rule({
    name = "anim-wlogout",
    match = {
        class = "^wlogout$",
    },
    animation = "slide up",
})

hl.window_rule({
    name = "opacity-apps",
    match = {
        class = "^(code|kitty|vesktop|youtube-music|thunar|zed|nemo)$",
    },
    opacity = "0.93 0.93",
})

hl.bind("SUPER + Return", hl.dsp.exec_cmd(term))
hl.bind("SUPER + SHIFT + Return", hl.dsp.exec_cmd(term .. " -f"))
hl.bind("SUPER + ALT + Return", hl.dsp.exec_cmd(term .. " -s"))
hl.bind("SUPER + T", hl.dsp.exec_cmd(term .. " -F"))

hl.bind("SUPER + N", hl.dsp.exec_cmd(files))
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd(editor))
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd(browser))

hl.bind("SUPER + D", hl.dsp.exec_cmd(rofi_launcher))
hl.bind("SUPER + R", hl.dsp.exec_cmd(rofi_runner))
hl.bind("SUPER + M", hl.dsp.exec_cmd(rofi_music))
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd(rofi_network))
hl.bind("SUPER + X", hl.dsp.exec_cmd(rofi_powermenu))
hl.bind("SUPER + A", hl.dsp.exec_cmd(rofi_screenshot))

hl.bind("SUPER + P", hl.dsp.exec_cmd(colorpicker))
hl.bind("SUPER + E", hl.dsp.exec_cmd(emojipicker))
hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd(lockscreen))
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd(background_swap))
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd(waybar_themes))
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd(screen_mode))

hl.bind("SUPER + SHIFT + EQUAL", hl.dsp.window.move({ workspace = "special" }))
hl.bind("SUPER + EQUAL", hl.dsp.workspace.toggle_special(""))

hl.bind("SUPER + SHIFT + I", hl.dsp.exec_cmd(cheatsheet))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(volume .. " --toggle-mic"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play"))
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl pause"))

hl.bind("Print", hl.dsp.exec_cmd(screenshot .. " --now"))
hl.bind("ALT + Print", hl.dsp.exec_cmd(screenshot .. " --in5"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd(screenshot .. " --in10"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(screenshot .. " --win"))
hl.bind("SUPER + Print", hl.dsp.exec_cmd(screenshot .. " --area"))

hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("CTRL + ALT + Delete", hl.dsp.exit())
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind("SUPER + F", hl.dsp.exec_cmd(notifycmd .. " 'Fullscreen Mode'"))
hl.bind("SUPER + S", hl.dsp.window.pseudo())
hl.bind("SUPER + S", hl.dsp.exec_cmd(notifycmd .. " 'Pseudo Mode'"))
hl.bind("SUPER + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind("SUPER + Space", hl.dsp.window.center())

hl.bind("SUPER + left", hl.dsp.focus({ direction = "left" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "right" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "up" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "down" }))

hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind("SUPER + CTRL + left", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + right", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + up", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind("SUPER + CTRL + down", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })

hl.bind("SUPER + ALT + left", hl.dsp.window.move({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + ALT + right", hl.dsp.window.move({ x = 20, y = 0, relative = true }), { repeating = true })
hl.bind("SUPER + ALT + up", hl.dsp.window.move({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind("SUPER + ALT + down", hl.dsp.window.move({ x = 0, y = 20, relative = true }), { repeating = true })

hl.bind("SUPER + Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind("SUPER + Tab", hl.dsp.window.bring_to_top())

hl.bind("SUPER + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind("SUPER + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind("SUPER + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind("SUPER + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind("SUPER + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind("SUPER + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind("SUPER + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind("SUPER + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind("SUPER + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("SUPER + minus", hl.dsp.focus({ workspace = 6 }))

hl.bind("SUPER + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind("SUPER + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind("SUPER + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind("SUPER + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind("SUPER + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind("SUPER + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind("SUPER + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind("SUPER + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))

hl.bind("SUPER + SHIFT + minus", hl.dsp.window.move({ workspace = 6 }))

hl.bind("SUPER + SHIFT + P", hl.dsp.window.pin())
hl.bind("SUPER + SHIFT + P", hl.dsp.exec_cmd(notifycmd .. " 'Toggled Pin'"))
hl.bind("SUPER + SHIFT + S", hl.dsp.window.swap({ next = true }))
hl.bind("switch:Lid Switch", hl.dsp.exec_cmd("echo \"Lid Switch\""), { locked = true })
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd(lockscreen), { locked = true })

hl.bind("SUPER + mouse:272", hl.dsp.window.drag())
hl.bind("SUPER + mouse:273", hl.dsp.window.resize())

hl.bind("SUPER + ALT + H", hl.dsp.window.move({ workspace = "special:minimized", follow = false }))

hl.bind("SUPER + ALT + M", hl.dsp.workspace.toggle_special("minimized"))

hl.bind("SUPER + ALT + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))

hl.bind("SUPER + ALT + Return", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))

hl.config({
    general = {
        border_size = hypr_border_size,
        gaps_in = hypr_gaps_in,
        gaps_out = hypr_gaps_out,
        col = {
            active_border = { colors = {"rgba(b4a1dbff)", "rgba(d04e9dff)"}, angle = 45 },
            inactive_border = "rgba(1e2030ff)",
        },
        layout = "dwindle",
    },
    ---- Decoration -------------------------------------------------
    decoration = {
        rounding = hypr_rounding,
        active_opacity = 1.0,
        inactive_opacity = 0.8,
        fullscreen_opacity = 1.0,
        dim_inactive = false,
        dim_strength = 0.5,
        blur = {
            enabled = true,
            size = 6,
        },
    },
    ---- Animations -------------------------------------------------
    animations = {
        enabled = true,
    },
    ---- Input: Keyboard, Mouse, Touchpad ---------------------------
    input = {
        kb_model = "",
        kb_layout = "us",
        kb_variant = "",
        kb_options = "",
        kb_rules = "",
        kb_file = "",
        numlock_by_default = false,
        repeat_rate = 25,
        repeat_delay = 600,
        sensitivity = 0.5,
        accel_profile = "adaptive",
        force_no_accel = false,
        left_handed = false,
        scroll_method = "2fg",
        scroll_button = 0,
        natural_scroll = false,
        follow_mouse = 1,
        float_switch_override_focus = 1,
        touchpad = {
            disable_while_typing = true,
            natural_scroll = true,
            scroll_factor = 1.0,
            middle_button_emulation = false,
            clickfinger_behavior = false,
            tap_to_click = true,
            drag_lock = false,
        },
        touchdevice = {
            transform = 0,
            output = "",
        },
    },
    ---- Workspace Gestures -----------------------------------------
    gestures = {
        workspace_swipe_distance = 300,
        workspace_swipe_invert = true,
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_cancel_ratio = 0.5,
        workspace_swipe_create_new = true,
        workspace_swipe_forever = false,
    },
    ---- Miscellaneous ----------------------------------------------
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = false,
        vrr = 1,
        mouse_move_enables_dpms = false,
        always_follow_on_dnd = true,
        layers_hog_keyboard_focus = true,
        animate_manual_resizes = false,
        disable_autoreload = false,
        enable_swallow = false,
        swallow_regex = "",
        focus_on_activate = true,
    },
    ---- Binds ------------------------------------------------------
    binds = {
        pass_mouse_when_bound = false,
        scroll_event_delay = 300,
        workspace_back_and_forth = false,
        allow_workspace_cycles = false,
    },
    ---- Debug (Only for developers) --------------------------------
    debug = {
        overlay = false,
        damage_blink = false,
        disable_logs = false,
        disable_time = true,
    },
    ---- Blurring Layer Surfaces ------------------------------------
    ---- Output -----------------------------------------------------
    -- Example : 
    --monitor = eDP-1,1920x1080@60,0x0,1
    --monitor = eDP-1,addreserved,10,10,10,10
    --monitor = eDP-1,transform,0
    --workspace = eDP-1,1
    --wsbind = 5,DP-1
    --wsbind = name:secret,DP-2
    ---- Layout : Dwindle -------------------------------------------
    dwindle = {
        force_split = 0,
        special_scale_factor = 1.0,
        split_width_multiplier = 1.0,
        --	no_gaps_when_only = false
        use_active_for_splits = true,
    },
    ---- Layout : Master --------------------------------------------
    master = {
        special_scale_factor = 1.0,
        new_on_top = false,
        orientation = "left",
    },
    ---- Window Rules -----------------------------------------------
    ---- Keybindings ------------------------------------------------
    -- -- Terminal --
    -- -- Apps --
    -- -- Rofi --
    -- bindr = SUPER, SUPER_L, exec, $rofi_launcher
    -- -- Wofi --
    -- bindr = SUPER, SUPER_L, exec, $wofi_menu
    -- bind  = SUPER, D,       exec, $wofi_menu
    -- bind = SUPER, X,       exec, $wofi_powermenu
    -- bind  = SUPER, A,       exec, $wofi_screenshot
    -- -- Misc --
    --bind = SUPER,    N, exec, nm-connection-editor
    --bind = SUPER,    X, exec, $wlogout
    -- -- Scratchpad --
    -- -- CHEATSHEET --
    -- -- Function keys --
    -- -- Screenshots --
    -- -- Hyprland --
    -- bind = SUPER,       C,      killactive,
    -- Change Focus
    -- Move Active
    -- Resize Active
    -- Move Active (Floating Only)
    -- Switch between windows
    -- Workspaces
    -- Send to Workspaces
    -- Change Workspace Mode
    -- Misc
    -- bind = SUPER + SHIFT, O, toggleopaque
    ---- Mouse Buttons ----------------------------------------------
    ---- Startup ----------------------------------------------------
    -- =================================================
    -- Window controls
    -- =================================================
    -- Minimize / hide active window
    -- Show / hide minimized windows
    -- Maximize / restore (Waybar tetap terlihat)
    -- True fullscreen / restore
    -- =================================================
    -- Window controls - Fedora Hyprland
    -- =================================================
    -- Hide/minimize window aktif
    -- Tampilkan/sembunyikan minimized workspace
    -- Maximize / restore
    -- Fullscreen / restore
    -- Wallpaper - Fedora Hyprland
})

hl.on("hyprland.start", function()
    hl.exec_cmd("~/.config/hypr/scripts/startup")
    hl.exec_cmd("hyprpaper")
end)

